//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hundsun.Framework.Platform.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hundsun.Framework.Platform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - [ 当前活动页 - {1} ] 的本地化字符串。
        /// </summary>
        internal static string CurrentPage {
            get {
                return ResourceManager.GetString("CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒生统一客户端开发平台 V1.0 的本地化字符串。
        /// </summary>
        internal static string FormCaption {
            get {
                return ResourceManager.GetString("FormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后保存页 的本地化字符串。
        /// </summary>
        internal static string LastDocument {
            get {
                return ResourceManager.GetString("LastDocument", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 设置(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示消息 的本地化字符串。
        /// </summary>
        internal static string TipMessage {
            get {
                return ResourceManager.GetString("TipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁 的本地化字符串。
        /// </summary>
        internal static string UnLock {
            get {
                return ResourceManager.GetString("UnLock", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap 棕色menu {
            get {
                object obj = ResourceManager.GetObject("棕色menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 棕色status {
            get {
                object obj = ResourceManager.GetObject("棕色status", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 棕色toolbar {
            get {
                object obj = ResourceManager.GetObject("棕色toolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 浅蓝menu {
            get {
                object obj = ResourceManager.GetObject("浅蓝menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 浅蓝status {
            get {
                object obj = ResourceManager.GetObject("浅蓝status", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 浅蓝toolbar {
            get {
                object obj = ResourceManager.GetObject("浅蓝toolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 浪漫menu {
            get {
                object obj = ResourceManager.GetObject("浪漫menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 浪漫status {
            get {
                object obj = ResourceManager.GetObject("浪漫status", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 浪漫toolbar {
            get {
                object obj = ResourceManager.GetObject("浪漫toolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 默认menu {
            get {
                object obj = ResourceManager.GetObject("默认menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 默认status {
            get {
                object obj = ResourceManager.GetObject("默认status", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 默认toolbar {
            get {
                object obj = ResourceManager.GetObject("默认toolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
