//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hundsun.Framework.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hundsun.Framework.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 会员证书不能为空，请选择! 的本地化字符串。
        /// </summary>
        internal static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，请求解析失败，请重新尝试！ 的本地化字符串。
        /// </summary>
        internal static string chixResponsePacket {
            get {
                return ResourceManager.GetString("chixResponsePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap enter {
            get {
                object obj = ResourceManager.GetObject("enter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 系统初始化完成，请登录! 的本地化字符串。
        /// </summary>
        internal static string InitEnd {
            get {
                return ResourceManager.GetString("InitEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T2通信初始化未成功，请重试! 的本地化字符串。
        /// </summary>
        internal static string InitFail {
            get {
                return ResourceManager.GetString("InitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H5通信初始化未成功，请重试! 的本地化字符串。
        /// </summary>
        internal static string InitH5Fail {
            get {
                return ResourceManager.GetString("InitH5Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化H5通信... 的本地化字符串。
        /// </summary>
        internal static string InitH5Message {
            get {
                return ResourceManager.GetString("InitH5Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H5通信初始化成功! 的本地化字符串。
        /// </summary>
        internal static string InitH5OK {
            get {
                return ResourceManager.GetString("InitH5OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化T2通信... 的本地化字符串。
        /// </summary>
        internal static string InitMessage {
            get {
                return ResourceManager.GetString("InitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T2通信初始化成功! 的本地化字符串。
        /// </summary>
        internal static string InitOK {
            get {
                return ResourceManager.GetString("InitOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap KeyBoardLeave {
            get {
                object obj = ResourceManager.GetObject("KeyBoardLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap leave {
            get {
                object obj = ResourceManager.GetObject("leave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 用户帐号或密码有误，请重新输入! 的本地化字符串。
        /// </summary>
        internal static string LoginWrong {
            get {
                return ResourceManager.GetString("LoginWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员帐号不能为空，请选择! 的本地化字符串。
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap settinghover {
            get {
                object obj = ResourceManager.GetObject("settinghover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap settingleave {
            get {
                object obj = ResourceManager.GetObject("settingleave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不能为空！ 的本地化字符串。
        /// </summary>
        internal static string txtNew {
            get {
                return ResourceManager.GetString("txtNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码不能为空！ 的本地化字符串。
        /// </summary>
        internal static string txtOld {
            get {
                return ResourceManager.GetString("txtOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码不能为空！ 的本地化字符串。
        /// </summary>
        internal static string txtRepeat {
            get {
                return ResourceManager.GetString("txtRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新旧密码不能相同！ 的本地化字符串。
        /// </summary>
        internal static string txtSame {
            get {
                return ResourceManager.GetString("txtSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap updateCancel1 {
            get {
                object obj = ResourceManager.GetObject("updateCancel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap updateCancel2 {
            get {
                object obj = ResourceManager.GetObject("updateCancel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap updateOK1 {
            get {
                object obj = ResourceManager.GetObject("updateOK1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap updateOK2 {
            get {
                object obj = ResourceManager.GetObject("updateOK2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 用户帐号不能为空，请输入! 的本地化字符串。
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码不能为空，请输入! 的本地化字符串。
        /// </summary>
        internal static string UserPwd {
            get {
                return ResourceManager.GetString("UserPwd", resourceCulture);
            }
        }
    }
}
